//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Orders;
using TestApiNet8.Domain.Entities;

namespace Services.Orders
{
    public interface IOrdersService
    {
        Task<OrderViewModel> AddAsync(OrderCreationDto orderCreationDto);
        Task<List<OrderViewModel>> GetAllAsync();
        Task<ListResult<OrderViewModel>> FilterAsync(PaginationOptions filter);
        Task<OrderViewModel> GetByIdAsync(int id);
        Task<OrderViewModel> UpdateAsync(int id, OrderModificationDto orderModificationDto);
        Task<OrderViewModel> DeleteAsync(int id);
    }
}