namespace EntityCore.Tools.Common
{
    public static class HeaderGenerator
    {
        private const string CSharpHeader = @"//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

"; // Extra newline at the end is important

        private const string RazorHeader = @"@*-----------------------------------------------------------------------*@
@* This file is autogenerated by EntityCore*@
@* <auto-generated />*@
@*-----------------------------------------------------------------------*@

"; // Extra newline at the end is important

        public static string PrependHeader(string content, bool isRazor)
        {
            if (isRazor)
            {
                return RazorHeader + content;
            }
            return CSharpHeader + content;
        }
    }
}
