//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using TestApiNet8.Domain.Entities;

namespace DataTransferObjects.Orders;

public class OrderModificationDto
{
	public int UserId { get; set; }
	public decimal TotalAmount { get; set; }
	public OrderStatus Status { get; set; }
}
