//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using TestApiNet8.Domain.Entities;

namespace DataTransferObjects.Orders;

public class OrderViewModel
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public User User { get; set; }
    public decimal TotalAmount { get; set; }
    public OrderStatus Status { get; set; }
}
