using Xunit;
using EntityCore.Test.Entities;
using EntityCore.Tools.Views;

namespace EntityCore.Test.Views
{
    public class ViewTest
    {
        private const string ExpectedRazorHeader = @"@*-----------------------------------------------------------------------*@
@* This file is autogenerated by EntityCore*@
@* <auto-generated />*@
@*-----------------------------------------------------------------------*@

"; // Extra newline is important

        [Fact]
        public void Should_Generate_Filter_View_With_Header()
        {
            // Arrange
            var filterGenerator = new Filter(typeof(SimpleEntity));

            // Act
            string generateResult = filterGenerator.Generate();

            // Assert
            Assert.StartsWith(ExpectedRazorHeader, generateResult);
        }

        [Fact]
        public void Should_Generate_Create_View_With_Header()
        {
            // Arrange
            var createGenerator = new Create(typeof(SimpleEntity));

            // Act
            string generateResult = createGenerator.Generate();

            // Assert
            Assert.StartsWith(ExpectedRazorHeader, generateResult);
        }

        [Fact]
        public void Should_Generate_Details_View_With_Header()
        {
            // Arrange
            var detailsGenerator = new Details(typeof(SimpleEntity));

            // Act
            string generateResult = detailsGenerator.Generate();

            // Assert
            Assert.StartsWith(ExpectedRazorHeader, generateResult);
        }
    }
}
