name: Publish .NET Package to NuGet

on:
  pull_request:
    types: [closed]
    branches:
      - prod

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          7.0.x
          8.0.x
          9.0.x

    - name: Publish packages for multiple versions
      run: |
        for version in 7 8 9
        do
          dotnet build src/EntityCore.Tools/EntityCore.Tools.csproj --configuration Release -p:Version=${version}.0.0
          dotnet pack src/EntityCore.Tools/EntityCore.Tools.csproj --configuration Release -p:Version=${version}.0.0 --output ./nupkg
        done

    - name: Publish package to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
