name: Publish .NET Package to NuGet

on:
  pull_request:
    types: [closed]
    branches:
      - prod

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          7.0.x
          8.0.x
          9.0.x

    - name: Extract version from .csproj
      id: extract_version
      run: |
        VERSION=$(grep -oP '(?<=<Version>)[^<]+' src/EntityCore.Tools/EntityCore.Tools.csproj)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Publish packages for multiple .NET versions
      run: |
        for dotnet_version in 7 8 9
        do
          NEW_VERSION="${dotnet_version}.${VERSION#*.}"
          echo "Building and packing version $NEW_VERSION for .NET $dotnet_version"

          dotnet build src/EntityCore.Tools/EntityCore.Tools.csproj --configuration Release -p:Version=$NEW_VERSION
          dotnet pack src/EntityCore.Tools/EntityCore.Tools.csproj --configuration Release -p:Version=$NEW_VERSION --output ./nupkg
        done

    - name: Publish package to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
